name: Run Python Code with Cache

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  execute-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: prime-cache-1fe03f3
        id: cache-python-deps
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-1fe03f3-${{ runner.os }}

      - name: Echo cache hit/miss result
        run: echo "Cache hit:${{ steps.cache-python-deps.outputs.cache-hit }}"

      - name: Install dependencies
        if: steps.cache-python-deps.outputs.cache-hit != 'true'
        run: pip install requests

      - name: 23f2003834@ds.study.iitm.ac.in
        run: python code.py
